'use strict';
/* MORNING BRIEF — compiled fresh every day at wake time (dashboard + email). */
const dbm = require('./db');
const cfgm = require('./config');
const brain = require('./brain');
const { dayKey, timeStr, dayLabel, minutesOfDay, snippet } = require('./util');

async function weather(cfg) {
  try {
    const { lat, lon } = cfg.owner.location || {};
    const ctl = new AbortController(); setTimeout(() => ctl.abort(), 4000);
    const res = await fetch(`https://api.open-meteo.com/v1/forecast?latitude=${lat}&longitude=${lon}&current=temperature_2m,weather_code&daily=temperature_2m_max,temperature_2m_min,precipitation_probability_max&timezone=auto&forecast_days=1`, { signal: ctl.signal });
    const j = await res.json();
    if (!j.current) return null;
    return { temp: Math.round(j.current.temperature_2m), code: j.current.weather_code, max: Math.round(j.daily.temperature_2m_max[0]), min: Math.round(j.daily.temperature_2m_min[0]), rain: j.daily.precipitation_probability_max[0] };
  } catch (_) { return null; }
}

async function generate({ trigger = 'manual' } = {}) {
  const cfg = cfgm.load();
  const db = dbm.load();
  const tz = cfg.owner.timezone;
  const now = Date.now();
  const today = dayKey(now, tz);
  const since = now - 16 * 36e5; // "overnight" window

  const w = await weather(cfg);

  // ---- Gather ----
  const events = db.find('events', e => dayKey(e.start, tz) === today).sort((a, b) => a.start - b.start);
  const overnightEmails = db.find('emails', e => e.receivedAt >= since).sort((a, b) => b.receivedAt - a.receivedAt);
  const overnightMsgs = db.find('messages', x => x.sentAt >= since).sort((a, b) => b.sentAt - a.sentAt);
  const hot = [...overnightEmails, ...overnightMsgs].filter(x => x.priority === 'high');
  const openTasks = db.find('tasks', t => !t.done);
  const unplayed = overnightEmails.filter(e => !e.read);

  const fmtEvent = (e) => {
    const icon = e.calendar === 'Business' ? '🏪' : e.calendar === 'Personal' ? '🏠' : '💼';
    const att = (e.attendees || []).length ? ` — ${(e.attendees || []).slice(0, 3).join(', ')}` : '';
    return `- ${icon} **${timeStr(e.start, tz)}–${timeStr(e.end, tz)}** ${e.title}${e.location ? ` · ${e.location}` : ''}${att}`;
  };

  const workEvents = events.filter(e => e.calendar === 'Work');
  const bizEvents = events.filter(e => e.calendar === 'Business');
  const otherEvents = events.filter(e => e.calendar !== 'Work' && e.calendar !== 'Business');

  const focusTopics = brain.extractTopics(overnightEmails.map(e => e.subject).join(' ') + ' ' + overnightMsgs.map(x => x.text).join(' '), 6);

  // ---- Compose ----
  const md = [];
  md.push(`# ☀️ Morning Brief — ${dayLabel(now, tz)}`);
  md.push(`_Prepared by ARIA at ${timeStr(now, tz)} (${tz}) · trigger: ${trigger}_`);
  if (w) md.push(`\n**${cfg.owner.location?.label || ''}** — ${w.temp}°C now (high ${w.max}° / low ${w.min}°) · rain ${w.rain}%`);

  md.push(`\n## ⚡ The one thing\n${oneThing(events, hot, openTasks, tz)}`);

  md.push(`\n## 🔥 Needs you first (${hot.length})`);
  md.push(hot.length ? hot.slice(0, 5).map(x => x.subject
    ? `- 🔴 **${x.subject}** — ${x.fromName || x.from} (${x.source})`
    : `- 🔴 **${x.channel}** — ${x.from}: ${snippet(x.text, 90)}`).join('\n')
    : '- Nothing urgent overnight. Start calmly.');

  md.push(`\n## 📅 Today's schedule (${events.length})`);
  if (workEvents.length) md.push(`**Day job**\n${workEvents.map(fmtEvent).join('\n')}`);
  if (bizEvents.length) md.push(`\n**Business**\n${bizEvents.map(fmtEvent).join('\n')}`);
  if (otherEvents.length) md.push(`\n**Personal**\n${otherEvents.map(fmtEvent).join('\n')}`);
  if (!events.length) md.push('- No meetings. Protect the deep work.');

  md.push(`\n## 📥 Overnight (${unplayed.length} unread emails · ${overnightMsgs.length} messages)`);
  md.push(overnightEmails.slice(0, 6).map(e => `- **${e.subject}** — ${e.fromName || e.from} _[${e.context || 'work'}${e.priority === 'high' ? ' · URGENT' : ''}]_`).join('\n') || '- Inbox quiet.');
  md.push(overnightMsgs.slice(0, 5).map(x => `- **${x.channel}** · ${x.from}: ${snippet(x.text, 80)}`).join('\n') || '');

  md.push(`\n## 🎯 Priorities for today`);
  const tops = (openTasks.length ? openTasks : priorityFallback(overnightEmails, overnightMsgs)).slice(0, 3);
  md.push(tops.map((t, i) => `${i + 1}. ${t.title || t}${t.due ? ` _(due ${new Date(t.due).toLocaleDateString('en-GB', { timeZone: tz })})_` : ''}`).join('\n') || '1. Set the day\'s intent in the Assistant.');

  md.push(`\n## 🧠 What your second brain is tracking`);
  md.push(focusTopics.length ? focusTopics.map(t => `\`${t}\``).join(' · ') : 'Growing quietly — capture notes anytime.');

  md.push(`\n---\n_Generated by ARIA OS · ${new Date(now).toISOString()}_`);

  const brief = {
    id: `brief-${today}-${trigger}-${Math.floor(minutesOfDay(now, tz))}`,
    date: today, generatedAt: now, trigger,
    markdown: md.join('\n'),
    meta: { events: events.length, emails: unplayed.length, messages: overnightMsgs.length, hot: hot.length }
  };
  db.upsert('briefs', brief);
  dbm.load().meta.lastBriefDate = today;
  dbm.save();

  // Brain keeps a memory of the brief
  brain.ingestNote({ title: `Morning brief — ${today}`, content: brief.markdown, source: 'system', kind: 'brief', tags: ['brief'], refId: brief.id });
  brain.autoGrow();

  // Email delivery
  if (cfg.brief.email) {
    const { sendBrief } = require('./email');
    brief.emailStatus = await sendBrief(cfg, brief);
    db.upsert('briefs', brief);
  }
  // Push notification to installed devices
  try {
    const { pushAll } = require('./push');
    brief.pushStatus = await pushAll({ title: '☀️ Morning Brief ready', body: `${brief.meta.hot} urgent · ${brief.meta.events} events today — tap to read.`, url: '/#/briefs' });
    db.upsert('briefs', brief);
  } catch (_) {}
  return brief;
}

function oneThing(events, hot, tasks, tz) {
  if (hot.length) {
    const h = hot[0];
    return h.subject ? `Answer **${h.subject}** (${h.fromName || h.from}) before anything else — it's the hottest thread overnight.` : `Reply to **${h.from}** in ${h.channel} — high-signal message waiting.`;
  }
  const first = events.find(e => e.calendar === 'Work' && e.start > Date.now()) || events[0];
  if (first) return `Prep for **${first.title}** at ${timeStr(first.start, tz)}${(first.attendees || []).length ? ` — attendees: ${first.attendees.slice(0, 2).join(', ')}` : ''}.`;
  if (tasks.length) return `No meetings pulling at you — clear **${tasks[0].title}**.`;
  return `Clean slate. Pick the one move that grows the business and do it before noon.`;
}

function priorityFallback(emails, msgs) {
  return emails.slice(0, 3).map(e => ({ title: `Handle email: ${e.subject}`, due: null }));
}

module.exports = { generate, weather };
